# Generated by Django 3.2.5 on 2021-07-19 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('picture', models.ImageField(null=True, upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(max_length=250, null=True)),
                ('profession', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('screenshot2', models.ImageField(upload_to='images')),
                ('screenshot3', models.ImageField(upload_to='images')),
                ('screenshot4', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('design', models.FloatField(blank=True, default=0)),
                ('usability', models.FloatField(blank=True, default=0)),
                ('creativity', models.FloatField(blank=True, default=0)),
                ('content', models.FloatField(blank=True, default=0)),
                ('overall_score', models.FloatField(blank=True, default=0)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.FloatField()),
                ('usability', models.FloatField()),
                ('creativity', models.FloatField()),
                ('content', models.FloatField()),
                ('mobile', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
        ),
    ]
