# Generated by Django 3.2.5 on 2021-07-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
