# Generated by Django 3.2.5 on 2021-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_owner_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
