# Generated by Django 3.2.5 on 2021-07-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('project_image', models.ImageField(null=True, upload_to='images')),
                ('description', models.TextField(max_length=500, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
