# Generated by Django 3.2.5 on 2021-07-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project'),
        ('projects', '0002_auto_20210718_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
