# Generated by Django 3.2.5 on 2021-07-26 03:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo2',
        ),
        migrations.DeleteModel(
            name='Photo3',
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='shots'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='shots'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='shots'),
        ),
    ]
