# Generated by Django 3.2.5 on 2021-07-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210726_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='screenshot1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot3',
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.photo'),
        ),
    ]
