# Generated by Django 3.2.5 on 2021-07-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210726_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot1',
            field=models.ImageField(null=True, upload_to='projects'),
        ),
    ]
