# Generated by Django 3.2.5 on 2021-07-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210721_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability',
        ),
        migrations.AlterField(
            model_name='project',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
