# Generated by Django 3.2.5 on 2021-07-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210723_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='screenshot1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot4',
        ),
    ]
