# Generated by Django 3.2.5 on 2021-07-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_project_screenshot1'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot2',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot3',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot4',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
