# Generated by Django 3.2.5 on 2021-07-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210723_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
