# Generated by Django 3.2.5 on 2021-07-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210723_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.photo2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.photo3'),
        ),
    ]
